### ISSUE TITLE
Uncaught TypeError: this.editor.getBuffer is not a function

### ISSUE THREAD

**Issue by cbbrahm** [ponsfrilus/markdown-toc#7]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: macOS 11.6.1
**Thrown From**: [md-toc](https://github.com/ponsfrilus/md-toc) package 0.13.0

### Stack Trace

Uncaught TypeError: this.editor.getBuffer is not a function

```
At /Users/charliebluebrahm/.atom/packages/md-toc/lib/Toc.coffee:22

TypeError: this.editor.getBuffer is not a function
    at /packages/md-toc/lib/Toc.coffee:22:13)
    at /packages/md-toc/lib/md-toc.coffee:12:16)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:352326)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:350801)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:786918)
    at EventEmitter.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:794889)
    at EventEmitter.emit (events.js:223:5)
    at Object.onMessage (electron/js2c/renderer_init.js:115:818)
```

### Commands

```
     -6:42.9.0 snippets:expand (input.hidden-input)
     -6:42.9.0 editor:indent (input.hidden-input)
     -6:33.1.0 editor:newline (input.hidden-input)
     -6:26.3.0 autocomplete-plus:confirm (input.hidden-input)
     -6:22.8.0 core:move-right (input.hidden-input)
     -6:18.9.0 core:paste (input.hidden-input)
     -6:17.2.0 core:save (input.hidden-input)
  2x -5:35.9.0 tree-view:remove (div.header.list-item)
     -4:21.9.0 settings-view:uninstall-packages (div.tool-panel.tree-view)
     -3:58.6.0 markdown-preview:preview-file (span.name.icon.icon-file-text)
     -3:47 settings-view:uninstall-packages (input.hidden-input)
  5x -3:38.2.0 core:backspace (input.hidden-input)
     -1:26 atom-mdtoc:insert (div.tool-panel.tree-view)
     -1:14 settings-view:uninstall-packages (div.tool-panel.tree-view)
  5x -1:09.9.0 core:backspace (input.hidden-input)
     -0:06.6.0 md-toc:create (div.tool-panel.tree-view)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
md-toc 0.13.0 
```

**Comment by ponsfrilus** [comment]
@cbbrahm are you doing something in particular? I'm running same version of Atom and Electron:
```
Atom    : 1.58.0
Electron: 9.4.4
Chrome  : 83.0.4103.122
Node    : 12.14.1
```
and I can't reproduce your issue.
